apiVersion: apps/v1
kind: Deployment
metadata:
  name: phoenix
  namespace: default
  labels:
    app: phoenix
spec:
  selector:
    matchLabels:
      app: phoenix
  template:
    metadata:
      labels:
        app: phoenix
    spec:
      containers:
      - name: phoenix
        image: teorxiro/phx_api_prod:latest 
        ports:
        - containerPort: 4000 
        envFrom:
            - configMapRef:
                name: phoenix


