---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-token-secret
  namespace: default
type: Opaque
stringData:
  cloudflare-token: VVeXjgV-sYVFT8vAE6ngX6ZphsCKmvp5QevNqjmE # be sure you are generating an API token and not a global API key https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/#api-tokens